#!/usr/bin/env python3
"""stress_test.py -- randomized defect-injection stress test for SEED's guards (Law 2 at scale).

Generates disposable copies of this repo. Each trial either injects ONE known defect class
(ground truth: checker must go RED) or applies benign valid additions (ground truth: checker
must stay GREEN). Reports per-class detection and false-alarm rates. Deterministic via --seed.

Pre-registered bars (workflow/experiments/2026-08-09-guard-stress.md): 100% detection per
class, zero false alarms. Exit 1 on any miss or false alarm. ASCII output only.
"""
import argparse
import json
import random
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHECK = ROOT / "scripts" / "onboard_check.py"
SPEND = ROOT / "scripts" / "spend_check.py"
TODAY = datetime.now()


def run_check(root):
    r = subprocess.run([sys.executable, str(CHECK), "--root", str(root)],
                       capture_output=True, text=True)
    return r.returncode


def fresh_copy(tmp, name):
    dst = Path(tmp) / name
    shutil.copytree(ROOT, dst, ignore=shutil.ignore_patterns(
        ".git", "__pycache__", ".test-tmp"))
    return dst


def append(path, text):
    path.write_text(path.read_text(encoding="utf-8") + text, encoding="utf-8")


def date_str(days_ago=0):
    return (TODAY - timedelta(days=days_ago)).strftime("%Y-%m-%d")


# ---------------------------------------------------------------- benign additions
def benign_receipt(root, rng, i):
    (root / "workflow" / "receipts" / f"{date_str()}-stress-ok-{i}.md").write_text(
        "STATE:       DONE\n"
        f"OBJECT:      benign stress artifact {rng.randint(1000,9999)}\n"
        "EXACT_REF:   worktree-stress\n"
        "EVIDENCE:    generated by stress_test.py benign lane; self-evident\n"
        "PROGRESS:    INFRASTRUCTURE\n"
        "EFFECT:      exercises the clean path of the receipt linter\n"
        f"SESSION_ID:  stress-{rng.randint(1000,9999)}\n"
        "NEXT_OWNER:  none - terminal\n", encoding="utf-8")


def benign_gate(root, rng, i):
    kind = rng.choice(["ANSWERED", f"DEFERRED({date_str(-365)})"])
    append(root / "GATES.md",
           f"| G-STRESS-{i} | benign stress gate | human | {date_str(rng.randint(0, 30))} | {kind} |\n")


def benign_open_gate_fresh(root, rng, i):
    append(root / "GATES.md",
           f"| G-STRESSO-{i} | benign fresh open gate | human | {date_str(0)} | OPEN |\n")


def benign_dispatch(root, rng, i):
    d = root / "workflow" / "dispatches"
    d.mkdir(parents=True, exist_ok=True)
    (d / f"{date_str()}-stress-{i}.md").write_text(
        "TO:          stress-seat\nOBJECT:      benign dispatch\nEXACT_REF:   worktree-stress\n"
        "ACTION:      exercise the clean dispatch path\nACCEPTANCE:  python -c \"print('ok')\"\n"
        "FENCES:      none beyond repo\nFORECAST:    1 minute, 0 tokens, 1 attempt\n"
        "NEXT_EVENT:  none - terminal\n", encoding="utf-8")


def benign_experiment(root, rng, i):
    d = root / "workflow" / "experiments"
    d.mkdir(parents=True, exist_ok=True)
    (d / f"{date_str()}-stress-{i}.md").write_text(
        "HYPOTHESIS:      benign pending experiment\nOBJECT:          worktree-stress\n"
        "DEPLOYED_FORM:   local\nMEASUREMENT:     n=1 smoke\nPASS_BAR:        runs\n"
        "KILL_BAR:        crashes\nCOST:            0\nOUTCOME:         PENDING\n"
        "INDEPENDENT_REPRO: deterministic\n", encoding="utf-8")


def benign_handoff(root, rng, i):
    (root / "workflow" / "handoffs" / f"{date_str()}-stress-{i}.md").write_text(
        "# RESUME HERE - stress benign\n\n## THE WHOLE JOB, IN FOUR LINES\n1. a\n2. b\n3. c\n4. d\n\n"
        "## BINDING RULES RIGHT NOW\nnone\n\n## EVERY NUMBER WORTH CITING\nnone yet\n\n"
        "## OPEN QUESTIONS\n1. none\n\n## WHAT NOT TO DO\nnothing\n", encoding="utf-8")


BENIGN = [benign_receipt, benign_gate, benign_open_gate_fresh,
          benign_dispatch, benign_experiment, benign_handoff]


# ---------------------------------------------------------------- defect classes
def d_missing_path(root, rng):
    victim = rng.choice(["LAWS.md", "AGENTS.md", "GATES.md",
                         "workflow/canon/DECISIONS.md", "scripts/status.py"])
    (root / victim).unlink()


def d_stale_gate(root, rng):
    append(root / "GATES.md",
           f"| G-STALE-{rng.randint(10,99)} | stress stale gate | human | {date_str(rng.randint(3, 90))} | OPEN |\n")


def d_bad_status(root, rng):
    tok = rng.choice(["MAYBE", "OPENISH", "PENDING", "DEFERRED"])
    append(root / "GATES.md",
           f"| G-BADST-{rng.randint(10,99)} | stress bad status | human | {date_str(0)} | {tok} |\n")


def d_malformed_row(root, rng):
    append(root / "GATES.md", f"| G-MAL-{rng.randint(10,99)} | too few cells | human |\n")


def d_dup_gate(root, rng):
    row = f"| G-DUP-7 | duplicate | human | {date_str(0)} | ANSWERED |\n"
    append(root / "GATES.md", row + row)


def d_expired_deferral(root, rng):
    append(root / "GATES.md",
           f"| G-EXP-{rng.randint(10,99)} | expired deferral | human | {date_str(60)} | DEFERRED({date_str(rng.randint(1, 40))}) |\n")


def d_receipt_missing_field(root, rng):
    fields = {"STATE": "DONE", "OBJECT": "thing", "EXACT_REF": "worktree-stress",
              "EVIDENCE": "some output", "PROGRESS": "INFRASTRUCTURE",
              "EFFECT": "some effect", "SESSION_ID": "stress", "NEXT_OWNER": "none - terminal"}
    victim = rng.choice(["STATE", "OBJECT", "EXACT_REF", "EVIDENCE",
                         "PROGRESS", "EFFECT", "NEXT_OWNER"])
    del fields[victim]
    body = "".join(f"{k}: {v}\n" for k, v in fields.items())
    (root / "workflow" / "receipts" / f"{date_str()}-stress-miss.md").write_text(body, encoding="utf-8")


def d_receipt_bad_state(root, rng):
    tok = rng.choice(["WISHFUL", "MOSTLY-DONE", "OK"])
    (root / "workflow" / "receipts" / f"{date_str()}-stress-badstate.md").write_text(
        f"STATE: {tok}\nOBJECT: x\nEXACT_REF: worktree-stress\nEVIDENCE: y\n"
        "PROGRESS: INFRASTRUCTURE\nEFFECT: z\nSESSION_ID: s\nNEXT_OWNER: none - terminal\n",
        encoding="utf-8")


def d_receipt_effect_none(root, rng):
    (root / "workflow" / "receipts" / f"{date_str()}-stress-noeffect.md").write_text(
        "STATE: DONE\nOBJECT: x\nEXACT_REF: worktree-stress\nEVIDENCE: y\n"
        "PROGRESS: MEASUREMENT\nEFFECT: none\nSESSION_ID: s\nNEXT_OWNER: none - terminal\n",
        encoding="utf-8")


def d_receipt_no_session(root, rng):
    (root / "workflow" / "receipts" / f"{date_str()}-stress-nosession.md").write_text(
        "STATE: DONE\nOBJECT: x\nEXACT_REF: worktree-stress\nEVIDENCE: y\n"
        "PROGRESS: INFRASTRUCTURE\nEFFECT: z\nNEXT_OWNER: none - terminal\n", encoding="utf-8")


def d_retracted_cite(root, rng):
    spot = rng.choice([root / "docs" / "nested", root / "workflow" / "handoffs", root])
    spot.mkdir(parents=True, exist_ok=True)
    (spot / "stress-note.md").write_text(
        "Recorded value was EXAMPLE-999.9 at last check.\n", encoding="utf-8")


def d_dispatch_invalid(root, rng):
    d = root / "workflow" / "dispatches"
    d.mkdir(parents=True, exist_ok=True)
    victim = rng.choice(["ACCEPTANCE", "FORECAST", "FENCES"])
    lines = {"TO": "seat", "OBJECT": "thing", "EXACT_REF": "worktree-stress",
             "ACTION": "build", "ACCEPTANCE": "runs", "FENCES": "none",
             "FORECAST": "1m", "NEXT_EVENT": "none"}
    del lines[victim]
    (d / f"{date_str()}-stress-bad.md").write_text(
        "".join(f"{k}: {v}\n" for k, v in lines.items()), encoding="utf-8")


def d_experiment_bad(root, rng):
    d = root / "workflow" / "experiments"
    d.mkdir(parents=True, exist_ok=True)
    mode = rng.choice(["outcome", "repro"])
    outcome = "CELEBRATE" if mode == "outcome" else "PASS"
    repro = "someone" if mode == "outcome" else ""
    (d / f"{date_str()}-stress-bad.md").write_text(
        "HYPOTHESIS: x\nOBJECT: worktree-stress\nDEPLOYED_FORM: local\nMEASUREMENT: n=1\n"
        f"PASS_BAR: 1\nKILL_BAR: 0\nCOST: 0\nOUTCOME: {outcome}\nINDEPENDENT_REPRO: {repro}\n",
        encoding="utf-8")


def d_handoff_bad(root, rng):
    mode = rng.choice(["header", "heading"])
    if mode == "header":
        body = "# We are probably done\n\n## THE WHOLE JOB, IN FOUR LINES\n1. a\n"
    else:
        body = ("# RESUME HERE - broken\n\n## THE WHOLE JOB, IN FOUR LINES\n1. a\n\n"
                "## BINDING RULES RIGHT NOW\nnone\n\n## EVERY NUMBER WORTH CITING\nnone\n")
    (root / "workflow" / "handoffs" / f"{date_str()}-stress-bad.md").write_text(body, encoding="utf-8")


def d_template_gutted(root, rng):
    name = rng.choice(["DISPATCH.md", "RECEIPT.md", "EXPERIMENT.md"])
    path = root / "workflow" / "templates" / name
    body = path.read_text(encoding="utf-8")
    fields = {"DISPATCH.md": "ACCEPTANCE", "RECEIPT.md": "EVIDENCE", "EXPERIMENT.md": "KILL_BAR"}
    path.write_text(re.sub(rf"^{fields[name]}:.*$", "", body, flags=re.MULTILINE), encoding="utf-8")


def d_claim_unsupported(root, rng):
    append(root / "CLAIMS.md",
           f"| C-STRESS-{rng.randint(10,99)} | stress claim | SUPPORTED | would fail if X | no path given |\n")


def d_law_gutted(root, rng):
    path = root / "LAWS.md"
    body = path.read_text(encoding="utf-8")
    marker = rng.choice(["**Earned by:**", "**Enforcement:**"])
    idx = body.rfind(marker)
    path.write_text(body[:idx] + body[idx:].replace(marker, "**Gutted:**", 1), encoding="utf-8")


DEFECTS = {
    "missing-path": d_missing_path, "stale-gate": d_stale_gate, "bad-gate-status": d_bad_status,
    "malformed-gate-row": d_malformed_row, "duplicate-gate": d_dup_gate,
    "expired-deferral": d_expired_deferral, "receipt-missing-field": d_receipt_missing_field,
    "receipt-bad-state": d_receipt_bad_state, "receipt-effect-none": d_receipt_effect_none,
    "receipt-no-session": d_receipt_no_session, "retracted-cite": d_retracted_cite,
    "dispatch-invalid": d_dispatch_invalid, "experiment-bad": d_experiment_bad,
    "handoff-bad": d_handoff_bad, "template-gutted": d_template_gutted,
    "claim-unsupported": d_claim_unsupported, "law-gutted": d_law_gutted,
}


# ---------------------------------------------------------------- spend_check scenarios
def spend_scenarios(tmp, rng, n):
    results = []
    for i in range(n):
        root = Path(tmp) / f"spend-{i}"
        (root / "workflow" / "receipts").mkdir(parents=True)
        stale = rng.random() < 0.3
        stamp = date_str(rng.randint(10, 40)) if stale else date_str(rng.randint(0, 3))
        spend = rng.choice([5.0, 80.0, 150.0, 900.0])
        loops = rng.choice([0, 0, 1, 3])
        export = root / f"ccusage-{stamp}.json"
        daily = [{"period": date_str(k), "totalCost": spend / 7} for k in range(7)]
        export.write_text(json.dumps({"daily": daily}), encoding="utf-8")
        for j in range(loops):
            (root / "workflow" / "receipts" / f"{date_str()}-loop-{j}.md").write_text(
                "STATE: DONE\nPROGRESS: MEASUREMENT\nEVIDENCE: x\n", encoding="utf-8")
        r = subprocess.run([sys.executable, str(SPEND), "--root", str(root),
                            "--json", str(export), "--max-unconsumed-usd", "100"],
                           capture_output=True, text=True)
        expect_fail = stale or (spend >= 100 and loops == 0)
        ok = (r.returncode != 0) == expect_fail
        results.append((f"spend[{'stale' if stale else 'fresh'},${spend:.0f},{loops}loops]", ok, expect_fail))
    return results


# ---------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--trials", type=int, default=250)
    ap.add_argument("--seed", type=int, default=20260809)
    args = ap.parse_args()
    rng = random.Random(args.seed)

    stats = {name: [0, 0] for name in DEFECTS}   # caught, total
    false_alarms, clean_total = 0, 0
    failures = []

    with tempfile.TemporaryDirectory() as tmp:
        baseline = fresh_copy(tmp, "baseline")
        if run_check(baseline) != 0:
            print("ABORT: baseline copy is RED -- fix the repo before stress testing it")
            return 2
        shutil.rmtree(baseline)

        spend_n = max(10, args.trials // 10)
        main_trials = args.trials - spend_n

        for i in range(main_trials):
            is_defect = rng.random() < 0.7
            root = fresh_copy(tmp, f"t{i}")
            if is_defect:
                name = rng.choice(list(DEFECTS))
                DEFECTS[name](root, rng)
                caught = run_check(root) != 0
                stats[name][0] += int(caught)
                stats[name][1] += 1
                if not caught:
                    failures.append(f"MISS: {name} (trial {i})")
            else:
                for fn in rng.sample(BENIGN, rng.randint(1, 3)):
                    fn(root, rng, i)
                clean_total += 1
                if run_check(root) != 0:
                    false_alarms += 1
                    failures.append(f"FALSE ALARM: benign trial {i}")
            shutil.rmtree(root)

        spend_results = spend_scenarios(tmp, rng, spend_n)

    print(f"GUARD STRESS TEST -- seed {args.seed}, {args.trials} trials\n")
    print(f"{'defect class':<24} {'caught':>7} {'total':>6} {'rate':>7}")
    all_perfect = True
    for name, (caught, total) in sorted(stats.items()):
        rate = f"{100*caught/total:.0f}%" if total else "n/a"
        flag = "" if caught == total else "  << MISSED"
        if caught != total:
            all_perfect = False
        print(f"{name:<24} {caught:>7} {total:>6} {rate:>7}{flag}")
    print(f"\nclean trials: {clean_total}, false alarms: {false_alarms}")
    spend_ok = sum(1 for _, ok, _ in spend_results if ok)
    print(f"spend_check scenarios: {spend_ok}/{len(spend_results)} verdicts correct")
    for name, ok, _ in spend_results:
        if not ok:
            failures.append(f"SPEND WRONG VERDICT: {name}")
            all_perfect = False
    for f in failures:
        print("  " + f)
    ok = all_perfect and false_alarms == 0 and spend_ok == len(spend_results)
    print("\nSTRESS TEST " + ("PASSED -- pre-registered bars met (100% detection, 0 false alarms)"
                              if ok else "FAILED -- guard gaps found; green is not trusted until fixed + re-run"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
